export type AdmissionRow = { c: string; n: string; count: number };
export type AdmissionYear = { label: string; sourceNote: string; rows: AdmissionRow[] };
export type RecentAdmissionPost = { c: string; n: string; date: string; degree: '학부·기타' | '대학원' };

export const annualOrder = ['2025-2026','2023-2024','2022-2023','2021-2022','2020-2021'] as const;

export const annualResults: Record<string, AdmissionYear> = {
  '2025-2026': {
    label: '2025–2026 · 제8기',
    sourceNote: '학교 공식 게시물 「2025-2026 대학진학 현황」의 제8기 합격 현황(2025.09.18 현재).',
    rows: [
      {c:'한국',n:'서울대학교',count:2},
      {c:'한국',n:'고려대학교',count:5},
      {c:'한국',n:'연세대학교',count:6},
      {c:'한국',n:'이화여자대학교(의과대학)',count:1},
      {c:'한국',n:'성균관대학교',count:6},
      {c:'한국',n:'한양대학교',count:4},
      {c:'한국',n:'서강대학교',count:4},
      {c:'한국',n:'중앙대학교',count:1},
      {c:'한국',n:'경희대학교',count:1},
      {c:'한국',n:'한국외국어대학교',count:1},
      {c:'중국',n:'칭화대학교',count:1},
      {c:'중국',n:'Duke Kunshan University',count:1},
      {c:'홍콩',n:'The University of Hong Kong',count:2},
      {c:'홍콩',n:'Hong Kong University of Science and Technology',count:1},
      {c:'일본',n:'Waseda University',count:1},
      {c:'일본',n:'Keio University',count:1},
      {c:'미국',n:'University of Charleston',count:1},
      {c:'미국',n:'Iowa State University',count:1},
      {c:'미국',n:'New York University (NYU)',count:1},
      {c:'미국',n:'Purdue University',count:1},
      {c:'미국',n:'UC Berkeley',count:1},
      {c:'미국',n:'UC Davis',count:2},
      {c:'미국',n:'UC Irvine',count:1},
      {c:'미국',n:'UC Merced',count:1},
      {c:'미국',n:'UC Riverside',count:1},
      {c:'미국',n:'UC San Diego',count:1},
      {c:'미국',n:'UC Santa Barbara',count:1},
      {c:'미국',n:'UC Santa Cruz',count:2},
      {c:'미국',n:'University of North Carolina at Chapel Hill',count:1},
      {c:'미국',n:'University of Southern California',count:1},
    ],
  },
  '2023-2024': {
    label: '2023–2024',
    sourceNote: '학교 공식 연도별 대학진학 현황 표.',
    rows: [
      {c:'한국',n:'Yonsei University (연세대학교)',count:2},
      {c:'한국',n:'Sungkyunkwan University (성균관대학교)',count:2},
      {c:'한국',n:'Hanyang University (한양대학교)',count:1},
      {c:'한국',n:'Dongguk University (동국대학교)',count:2},
      {c:'한국',n:'Konkuk University (건국대학교)',count:1},
      {c:'한국',n:'Hongik University (홍익대학교)',count:1},
      {c:'홍콩',n:'HKU - The University of Hong Kong',count:3},
      {c:'홍콩',n:'HKUST - The Hong Kong University of Science and Technology',count:3},
      {c:'홍콩',n:'CUHK - The Chinese University of Hong Kong',count:2},
      {c:'홍콩',n:'CityU - City University of Hong Kong',count:2},
      {c:'미국',n:'Northeastern University',count:2},
      {c:'미국',n:'University of California, Irvine',count:1},
      {c:'미국',n:'University of California, Santa Cruz',count:1},
      {c:'미국',n:'University of California, Davis',count:3},
      {c:'미국',n:'University of California, Riverside',count:1},
      {c:'홍콩',n:'HKBU - Hong Kong Baptist University',count:1},
      {c:'싱가포르',n:'NUS - National University of Singapore',count:1},
      {c:'미국',n:'Emory University',count:1},
      {c:'미국',n:'Michigan State University',count:1},
      {c:'미국',n:'Penn State',count:2},
      {c:'미국',n:'University of Richmond',count:1},
      {c:'미국',n:'University of Rochester',count:1},
      {c:'미국',n:'University of Illinois Urbana-Champaign',count:1},
    ],
  },
  '2022-2023': {
    label: '2022–2023',
    sourceNote: '학교 공식 연도별 대학진학 현황 표.',
    rows: [
      {c:'한국',n:'Seoul National University (서울대학교)',count:2},
      {c:'한국',n:'KAIST (카이스트)',count:1},
      {c:'한국',n:'Korea University (고려대학교)',count:9},
      {c:'한국',n:'Yonsei University (연세대학교)',count:5},
      {c:'한국',n:'Sogang University (서강대학교)',count:4},
      {c:'한국',n:'Sungkyunkwan University (성균관대학교)',count:8},
      {c:'한국',n:'Hanyang University (한양대학교)',count:7},
      {c:'한국',n:'Chung-Ang University (중앙대학교)',count:4},
      {c:'한국',n:'Hankuk University of Foreign Studies (한국외국어대학교)',count:1},
      {c:'한국',n:'Konkuk University (건국대학교)',count:1},
      {c:'카타르',n:'Cornell University - Weill Cornell Medicine-Qatar',count:1},
      {c:'싱가포르',n:'National University of Singapore',count:3},
      {c:'미국',n:'Bard College',count:1},
      {c:'미국',n:'Beloit College',count:1},
      {c:'미국',n:'Case Western Reserve University',count:1},
      {c:'미국',n:'College of Wooster',count:1},
      {c:'미국',n:'Drexel University',count:1},
      {c:'미국',n:'Embry-Riddle Aeronautical University',count:1},
      {c:'미국',n:'Fordham University',count:1},
      {c:'미국',n:'Indiana University Bloomington',count:3},
      {c:'미국',n:'Knox College',count:1},
      {c:'미국',n:'Lawrence University',count:1},
      {c:'미국',n:'Mount Holyoke College',count:1},
      {c:'미국',n:'Michigan State University',count:3},
      {c:'미국',n:'University of Minnesota Twin Cities',count:2},
      {c:'미국',n:'New York University',count:1},
      {c:'UAE',n:'New York University Abu Dhabi',count:1},
      {c:'미국',n:'North Carolina State University',count:2},
      {c:'미국',n:'Ohio State University',count:4},
      {c:'미국',n:'Pennsylvania State University',count:5},
      {c:'미국',n:'Purdue University',count:5},
      {c:'미국',n:'State University of New York at Buffalo (SUNY Buffalo)',count:2},
      {c:'미국',n:'State University of New York, Stony Brook (SUNY Stony Brook)',count:2},
      {c:'미국',n:'Syracuse University',count:1},
      {c:'미국',n:'Texas A&M University',count:2},
      {c:'미국',n:'Union College',count:1},
      {c:'미국',n:'University of Iowa',count:1},
      {c:'미국',n:'University of Texas at Austin',count:1},
      {c:'미국',n:'University of California, Davis',count:3},
      {c:'미국',n:'University of California, Irvine',count:4},
      {c:'미국',n:'University of California, Los Angeles (UCLA)',count:1},
      {c:'미국',n:'University of California, San Diego',count:2},
      {c:'미국',n:'University of California, Santa Barbara',count:2},
      {c:'미국',n:'University of Florida',count:1},
      {c:'미국',n:'University of Illinois at Chicago',count:1},
      {c:'미국',n:'University of Illinois at Urbana-Champaign',count:1},
      {c:'미국',n:'University of Michigan',count:1},
      {c:'미국',n:'University of Richmond',count:1},
      {c:'미국',n:'University of Washington',count:1},
      {c:'미국',n:'Virginia Tech',count:2},
      {c:'캐나다',n:'University of British Columbia',count:1},
      {c:'캐나다',n:'University of Toronto',count:3},
      {c:'캐나다',n:'Western University',count:1},
      {c:'캐나다',n:'York University',count:1},
      {c:'일본',n:'Keio University',count:1},
      {c:'일본',n:'Waseda University',count:1},
      {c:'중국',n:'Duke Kunshan University',count:2},
      {c:'홍콩',n:'Chinese University of Hong Kong',count:7},
      {c:'홍콩',n:'City University of Hong Kong',count:6},
      {c:'홍콩',n:'Hong Kong University of Science and Technology',count:5},
      {c:'홍콩',n:'University of Hong Kong',count:1},
      {c:'네덜란드',n:'University of Amsterdam',count:1},
    ],
  },
  '2021-2022': {
    label: '2021–2022',
    sourceNote: '학교 공식 연도별 대학진학 현황 표.',
    rows: [
      {c:'한국',n:'Yonsei University (연세대학교)',count:2},
      {c:'한국',n:'Korea University (고려대학교)',count:1},
      {c:'한국',n:'Sungkyunkwan University (성균관대학교)',count:6},
      {c:'한국',n:'Sogang University (서강대학교)',count:3},
      {c:'한국',n:'Hanyang University (한양대학교)',count:4},
      {c:'한국',n:'Chung-Ang University (중앙대학교)',count:3},
      {c:'한국',n:'Hankuk University of Foreign Studies (한국외국어대학교)',count:1},
      {c:'한국',n:'Ewha Womans University (이화여자대학교)',count:1},
      {c:'한국',n:'Kyung Hee University (경희대학교)',count:1},
      {c:'한국',n:'Chungnam National University (충남대학교)',count:1},
      {c:'한국',n:'Chungbuk National University (충북대학교)',count:1},
      {c:'홍콩',n:'Hong Kong University of Science and Technology',count:3},
      {c:'중국',n:'Duke Kunshan University',count:2},
      {c:'홍콩',n:'City University of Hong Kong',count:2},
      {c:'미국',n:'Massachusetts College of Pharmacy and Health Sciences',count:1},
      {c:'미국',n:'Virginia Tech',count:1},
      {c:'미국',n:'University of Georgia',count:1},
      {c:'미국',n:'New York University, New York',count:2},
      {c:'미국',n:'University of Kansas',count:1},
      {c:'미국',n:'Michigan State University',count:1},
      {c:'홍콩',n:'University of Hong Kong',count:2},
      {c:'미국',n:'University of Illinois at Urbana-Champaign',count:2},
      {c:'홍콩',n:'The Chinese University of Hong Kong',count:1},
      {c:'미국',n:'Pennsylvania State University, Main Campus',count:2},
      {c:'미국',n:'Emory University',count:1},
      {c:'미국',n:'Rose-Hulman Institute of Technology',count:1},
      {c:'미국',n:'Ohio State University',count:1},
      {c:'미국',n:'University of Washington, Seattle',count:1},
      {c:'미국',n:'University of California, Irvine',count:1},
    ],
  },
  '2020-2021': {
    label: '2020–2021',
    sourceNote: '학교 공식 연도별 대학진학 현황 표.',
    rows: [
      {c:'한국',n:'Yonsei University (연세대학교)',count:2},
      {c:'한국',n:'Korea University (고려대학교)',count:4},
      {c:'한국',n:'Sogang University (서강대학교)',count:3},
      {c:'한국',n:'Sungkyunkwan University (성균관대학교)',count:6},
      {c:'한국',n:'Ewha Womans University (이화여자대학교)',count:1},
      {c:'한국',n:'Hanyang University (한양대학교)',count:4},
      {c:'한국',n:'Chung-Ang University (중앙대학교)',count:1},
      {c:'한국',n:'Konkuk University (건국대학교)',count:1},
      {c:'한국',n:'Kookmin University (국민대학교)',count:2},
      {c:'한국',n:'Hankuk University of Foreign Studies (한국외국어대학교)',count:1},
      {c:'한국',n:'Hongik University (홍익대학교)',count:1},
      {c:'한국',n:'Woosuk University (우석대학교)',count:1},
      {c:'UAE',n:'NYU Abu Dhabi',count:1},
      {c:'미국',n:'Arizona State University',count:1},
      {c:'미국',n:'Asbury University',count:1},
      {c:'미국',n:'Auburn University',count:1},
      {c:'미국',n:'California State University Northridge',count:1},
      {c:'미국',n:'DePaul University',count:1},
      {c:'미국',n:'Emerson College',count:1},
      {c:'미국',n:'Full Sail University',count:1},
      {c:'미국',n:'Indiana University Bloomington',count:1},
      {c:'미국',n:'Ohio University',count:1},
      {c:'미국',n:'Pennsylvania State University',count:1},
      {c:'미국',n:'Purdue University',count:2},
      {c:'미국',n:'San Francisco State University',count:1},
      {c:'미국',n:'Stony Brook University, New York',count:1},
      {c:'미국',n:'The University of Utah',count:1},
      {c:'미국',n:'University of Illinois at Chicago',count:1},
      {c:'미국',n:'University of Wisconsin-Milwaukee',count:1},
      {c:'싱가포르',n:'National University of Singapore',count:1},
      {c:'베트남',n:'Vin University',count:1},
      {c:'일본',n:'Waseda University',count:1},
      {c:'일본',n:'Hokkaido University',count:1},
      {c:'일본',n:'Okayama University',count:1},
      {c:'일본',n:'Ritsumeikan University',count:1},
      {c:'일본',n:'University of Tsukuba',count:1},
      {c:'중국',n:'Duke Kunshan University',count:3},
      {c:'중국',n:'Renmin University of China',count:2},
      {c:'중국',n:'Zhejiang University',count:2},
      {c:'캐나다',n:'University of Toronto',count:1},
      {c:'대만',n:'National Tsing Hua University',count:1},
      {c:'대만',n:'National Taiwan University',count:1},
      {c:'홍콩',n:'City University of Hong Kong',count:2},
      {c:'홍콩',n:'The Chinese University of Hong Kong',count:1},
      {c:'홍콩',n:'The Hong Kong University of Science and Technology',count:5},
    ],
  },
};

export const recentAdmissionPosts: RecentAdmissionPost[] = [
  {c:'한국',n:'서강대학교 · 2026학년도 후기',date:'2026-07-06',degree:'학부·기타'},
  {c:'한국',n:'중앙대학교 · 2026학년도 후기',date:'2026-06-29',degree:'학부·기타'},
  {c:'영국',n:'Liverpool John Moores University',date:'2026-06-20',degree:'학부·기타'},
  {c:'싱가포르',n:'National University of Singapore (NUS)',date:'2026-06-17',degree:'학부·기타'},
  {c:'한국',n:'성균관대학교 · 2026학년도 후기',date:'2026-06-16',degree:'학부·기타'},
  {c:'한국',n:'한양대학교 · 2026학년도 후기',date:'2026-06-08',degree:'학부·기타'},
  {c:'한국',n:'연세대학교 · 2026학년도 후기',date:'2026-06-08',degree:'학부·기타'},
  {c:'한국',n:'고려대학교 · 2026학년도 후기',date:'2026-06-08',degree:'학부·기타'},
  {c:'한국',n:'서울대학교 · 2026학년도 후기',date:'2026-05-21',degree:'학부·기타'},
  {c:'홍콩',n:'The University of Hong Kong · 국제경영학과',date:'2026-04-17',degree:'학부·기타'},
  {c:'영국',n:'University of Sunderland',date:'2026-03-24',degree:'학부·기타'},
  {c:'홍콩',n:'The University of Hong Kong',date:'2026-03-24',degree:'학부·기타'},
  {c:'호주',n:'Monash University',date:'2026-03-24',degree:'학부·기타'},
  {c:'미국',n:'Columbia University · 석사과정',date:'2026-03-15',degree:'대학원'},
  {c:'일본',n:'Waseda University',date:'2026-03-11',degree:'학부·기타'},
  {c:'미국',n:'University of Pennsylvania (UPenn) · 석사과정 성적우수장학생',date:'2026-03-10',degree:'대학원'},
  {c:'미국',n:'Johns Hopkins University (JHU) · 석사과정 성적우수장학생',date:'2026-03-10',degree:'대학원'},
  {c:'홍콩',n:'Hong Kong University of Science and Technology (HKUST)',date:'2025-12-18',degree:'학부·기타'},
  {c:'홍콩',n:'Hong Kong University of Science and Technology (HKUST)',date:'2025-12-18',degree:'학부·기타'},
  {c:'홍콩',n:'Hong Kong University of Science and Technology (HKUST)',date:'2025-12-11',degree:'학부·기타'},
  {c:'한국',n:'성균관대학교 의과대학 · 2026학년도 전기',date:'2025-09-12',degree:'학부·기타'},
  {c:'한국',n:'연세대학교 의과대학 · 2026학년도 전기',date:'2025-09-05',degree:'학부·기타'},
  {c:'한국',n:'이화여자대학교 의과대학 · 2026학년도 전기',date:'2025-09-05',degree:'학부·기타'},
];
